// let Graph = require('./graph.js');
// let Graph = require('./graph-directed.js');
let Graph = require('./graph-undirected.js');
let graph = new Graph();
graph.addNode(0);
graph.addNode(1);
graph.addNode(2);
graph.addNode(3);
graph.addEdge(1, 3);
graph.addEdge(1, 2);
graph.addEdge(0, 2);
graph.addEdge(3, 1);
graph.addEdge(3, 2);
graph.addEdge(3, 0);
graph.addEdge(2, 1);
graph.addEdge(2, 0);
graph.addEdge(4, 1);
graph.addEdge(0, 2);
graph.removeEdge(2, 1);
console.log(graph);
graph.removeNode(1);
console.log(graph);
